name: braiins-pool-exporter

services:
  avalonhome-prometheus-exporter:
    scale: 1

  prometheus:
    volumes:
      - ./prometheus/prometheus.miner.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    depends_on:
      - braiins-pool-exporter
      - avalonhome-prometheus-exporter
